server:
  port: 8082

spring:
  # 邮件配置
  mail:
    # 邮件服务器地址
    host: smtp.163.com
    protocol: smtp
    default-encoding: UTF-8
    # 授权码（在开通邮箱服务时获取）
    password:
    # 发送者邮箱地址
    username:
    port: 25
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    listener:
      simple:
        # 开启手动确认
        acknowledge-mode: manual
  # redis配置
  redis:
    timeout: 10000ms # 超时时间
    host: localhost
    port: 6379
    database: 0 # 选择哪个默认0库
    lettuce:
      pool:
        max-active: 1024 # 最大连接数，默认 8
        max-wait: 10000ms # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 200 # 最大空闲连接，默认 8
        min-idle: 5